export const doctorsDummyData = [
  {
    id: 1,
    name: "Dr. Aisha Khan",
    specialty: "Dermatologist",
    experience: 8,
    rating: 4.6,
    fees: 500,
    city: "Mumbai",
    location: "Andheri",
    languages: ["English", "Hindi"],
    availability: ["10:00 AM", "12:00 PM", "04:00 PM"],
    clinic: "Skin Care Clinic",
    profileImage: "https://i.pravatar.cc/100?img=5",
    bio: "Experienced dermatologist specializing in skin and hair treatments.",
    education: "MBBS, MD (Dermatology)"
  },
  {
    id: 2,
    name: "Dr. Raj Patel",
    specialty: "Orthopedic",
    experience: 12,
    rating: 4.8,
    fees: 700,
    city: "Pune",
    location: "Baner",
    languages: ["English", "Hindi", "Marathi"],
    availability: ["11:00 AM", "02:00 PM", "06:00 PM"],
    clinic: "Ortho Plus Hospital",
    profileImage: "https://i.pravatar.cc/100?img=12",
    bio: "Orthopedic surgeon with expertise in joint replacement.",
    education: "MBBS, MS (Orthopedics)"
  },
  {
    id: 3,
    name: "Dr. Priya Sharma",
    specialty: "Pediatrician",
    experience: 6,
    rating: 4.7,
    fees: 400,
    city: "Delhi",
    location: "Saket",
    languages: ["English", "Hindi"],
    availability: ["09:00 AM", "01:00 PM", "05:00 PM"],
    clinic: "Little Care Clinic",
    profileImage: "https://i.pravatar.cc/100?img=21",
    bio: "Caring pediatrician helping children with routine and specialized healthcare.",
    education: "MBBS, DCH"
  },
  {
    id: 4,
    name: "Dr. Sameer Malhotra",
    specialty: "Cardiologist",
    experience: 15,
    rating: 4.9,
    fees: 1000,
    city: "Mumbai",
    location: "Bandra",
    languages: ["English", "Hindi"],
    availability: ["10:30 AM", "01:30 PM", "05:30 PM"],
    clinic: "Heart Care Hospital",
    profileImage: "https://i.pravatar.cc/100?img=31",
    bio: "Expert cardiologist providing advanced cardiac care and consultation.",
    education: "MBBS, MD (Cardiology)"
  },
  {
    id: 5,
    name: "Dr. Neha Verma",
    specialty: "Gynecologist",
    experience: 10,
    rating: 4.8,
    fees: 600,
    city: "Bangalore",
    location: "Whitefield",
    languages: ["English", "Hindi", "Kannada"],
    availability: ["08:00 AM", "12:00 PM", "03:00 PM"],
    clinic: "Women Care Clinic",
    profileImage: "https://i.pravatar.cc/100?img=44",
    bio: "Specialist in women's health, pregnancy, and reproductive care.",
    education: "MBBS, MD (Gynecology)"
  },
  {
    id: 6,
    name: "Dr. Vikram Mehra",
    specialty: "Neurologist",
    experience: 18,
    rating: 4.9,
    fees: 1200,
    city: "Hyderabad",
    location: "Gachibowli",
    languages: ["English", "Hindi", "Telugu"],
    availability: ["11:00 AM", "03:00 PM", "07:00 PM"],
    clinic: "Neuro Spine Center",
    profileImage: "https://i.pravatar.cc/100?img=33",
    bio: "Senior Neurologist focusing on stroke recovery and migraine management.",
    education: "MBBS, DM (Neurology)"
  },
  {
    id: 7,
    name: "Dr. Ananya Iyer",
    specialty: "Ophthalmologist",
    experience: 7,
    rating: 4.5,
    fees: 450,
    city: "Chennai",
    location: "Adyar",
    languages: ["English", "Tamil", "Hindi"],
    availability: ["09:30 AM", "12:30 PM", "04:30 PM"],
    clinic: "Vision Eye Care",
    profileImage: "https://i.pravatar.cc/100?img=26",
    bio: "Dedicated eye specialist providing LASIK and cataract consultations.",
    education: "MBBS, MS (Ophthalmology)"
  },
  {
    id: 8,
    name: "Dr. Rahul Deshmukh",
    specialty: "General Physician",
    experience: 9,
    rating: 4.4,
    fees: 300,
    city: "Pune",
    location: "Kothrud",
    languages: ["English", "Hindi", "Marathi"],
    availability: ["08:30 AM", "11:30 AM", "05:30 PM"],
    clinic: "Family Health Clinic",
    profileImage: "https://i.pravatar.cc/100?img=68",
    bio: "Compassionate physician for chronic illness and general wellness.",
    education: "MBBS, DNB (Internal Medicine)"
  }
];